version: '3.8'

services:
  newsgator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsgator
    restart: always
    expose:
      - 3005
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3005

  ngnginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - newsgator
