version: '3.8'

services:
  newsgator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsgator
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000

  nginx:
    image: nginx:1.24
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - newsgator
